"""empty message

Revision ID: 96be1d05b541
Revises: 96be1d05b54e
Create Date: 2022-07-31 11:04:20.633777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96be1d05b541'
down_revision = '96be1d05b54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'date')
    op.add_column('events', sa.Column('date', sa.VARCHAR(
        length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'date')
    op.add_column('events', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###
