"""empty message

Revision ID: 96be1d05b54e
Revises: f4f345c50a41
Create Date: 2022-07-31 11:04:20.633777

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '96be1d05b54e'
down_revision = 'f4f345c50a41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookmarks', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmarks', sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
