"""empty message

Revision ID: a81d9845aa60
Revises: 2e6e61d6a88a
Create Date: 2022-07-27 13:14:55.025048

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'a81d9845aa60'
down_revision = '2e6e61d6a88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tickets_event_id_fkey', 'tickets', type_='foreignkey')
    op.create_foreign_key(None, 'tickets', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.create_foreign_key('tickets_event_id_fkey', 'tickets', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
