"""empty message

Revision ID: f4f345c50a41
Revises: bddba3eac011
Create Date: 2022-07-28 17:58:12.710128

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'f4f345c50a41'
down_revision = 'bddba3eac011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'event_url')
    op.add_column('tickets', sa.Column('event_url', sa.VARCHAR(
        length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'event_url')
    op.add_column('tickets', sa.Column('event_url', sa.VARCHAR(
        length=40), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
