"""empty message

Revision ID: ad27d94bcfc7
Revises: 7046ba0dffc8
Create Date: 2022-07-26 12:37:37.436700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad27d94bcfc7'
down_revision = '7046ba0dffc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('event_url', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'event_url')
    # ### end Alembic commands ###
