"""empty message

Revision ID: 4fe374bb6eee
Revises: a81d9845aa60
Create Date: 2022-07-27 13:22:34.593932

"""
from alembic import op
import sqlalchemy as sa
import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = '4fe374bb6eee'
down_revision = 'a81d9845aa60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_events_user_id_fkey', 'user_events', type_='foreignkey')
    op.create_foreign_key(None, 'user_events', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_events', type_='foreignkey')
    op.create_foreign_key('user_events_user_id_fkey', 'user_events', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
